### ISSUE TITLE
problem in prepro.py

### ISSUE THREAD

**Issue by RoroKA** [karpathy/neuraltalk2#155]
I'm trying to run the code on my data and I get this error message
when i invoke prepro.py
ValueError: Expecting property name: line 2 column 4 (char 6)

**Comment by RoroKA** [comment]
The complete error message:

Traceback (most recent call last):
  File "prepro.py", line 240, in <module>
    main(params)
  File "prepro.py", line 157, in main
    imgs = json.load(open(params['input_json'], 'r'))
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 2 column 4 (char 6)

Could you please help my?
Can any one send me a correct "coco_raw.json" to be able to continue working ?

**Comment by andevani** [comment]
Sample coco_raw.json.

[{"captions": ["10 kilometer per hour traffic sign.", "10 km/hr speed limit traffic sign"], "file_path":"val/10.jpg", "id": 10}, {"captions": ["20 kilometer per hour traffic sign.", "20 km/hr speed limit traffic sign"], "file_path":"val/20.jpg", "id": 20}, {"captions": ["30 kilometer per hour traffic sign.", "30 km/hr speed limit traffic sign"], "file_path":"val/30.jpg", "id": 30},{"captions": ["40 kilometer per hour traffic sign.", "40 km/hr speed limit traffic sign"], "file_path":"val/40.jpg", "id": 40}, {"captions": ["50 kilometer per hour traffic sign.", "50 km/hr speed limit traffic sign"], "file_path":"val/50.jpg", "id": 50}, {"captions": ["60 kilometer per hour traffic sign.", "60 km/hr speed limit traffic sign"], "file_path":"val/60.jpg", "id": 60}, {"captions": ["70 kilometer per hour traffic sign.", "70 km/hr speed limit traffic sign"], "file_path":"val/70.jpg", "id": 70}, {"captions": ["80 kilometer per hour traffic sign.", "80 km/hr speed limit traffic sign"], "file_path":"val/80.jpg", "id": 80}, {"captions": ["90 kilometer per hour traffic sign.", "90 km/hr speed limit traffic sign"], "file_path":"val/90.jpg", "id": 90}, {"captions": ["100 kilometer per hour traffic sign.", "100 km/hr speed limit traffic sign"], "file_path":"val/100.jpg", "id": 100}, {"captions": ["110 kilometer per hour traffic sign.", "110 km/hr speed limit traffic sign"], "file_path":"val/110.jpg", "id": 110}, {"captions": ["120 kilometer per hour traffic sign.", "120 km/hr speed limit traffic sign"], "file_path":"val/120.jpg", "id": 120}, {"captions": ["10 kilometer per hour traffic sign.", "10 km/hr speed limit traffic sign"], "file_path":"train/10.jpg", "id": 10}, {"captions": ["20 kilometer per hour traffic sign.", "20 km/hr speed limit traffic sign"], "file_path":"train/20.jpg", "id": 20}, {"captions": ["30 kilometer per hour traffic sign.", "30 km/hr speed limit traffic sign"], "file_path":"train/30.jpg", "id": 30},{"captions": ["40 kilometer per hour traffic sign.", "40 km/hr speed limit traffic sign"], "file_path":"train/40.jpg", "id": 40}, {"captions": ["50 kilometer per hour traffic sign.", "50 km/hr speed limit traffic sign"], "file_path":"train/50.jpg", "id": 50}, {"captions": ["60 kilometer per hour traffic sign.", "60 km/hr speed limit traffic sign"], "file_path":"train/60.jpg", "id": 60}, {"captions": ["70 kilometer per hour traffic sign.", "70 km/hr speed limit traffic sign"], "file_path":"train/70.jpg", "id": 70}, {"captions": ["80 kilometer per hour traffic sign.", "80 km/hr speed limit traffic sign"], "file_path":"train/80.jpg", "id": 80}, {"captions": ["90 kilometer per hour traffic sign.", "90 km/hr speed limit traffic sign"], "file_path":"train/90.jpg", "id": 90}, {"captions": ["100 kilometer per hour traffic sign.", "100 km/hr speed limit traffic sign"], "file_path":"train/100.jpg", "id": 100}, {"captions": ["110 kilometer per hour traffic sign.", "110 km/hr speed limit traffic sign"], "file_path":"train/110.jpg", "id": 110}, {"captions": ["120 kilometer per hour traffic sign.", "120 km/hr speed limit traffic sign"], "file_path":"train/120.jpg", "id": 120}]


I am using this for my data set. It is working perfectly.
