### ISSUE TITLE
 when I use the code to evaluate BLEU/METEOR/CIDEr scores,I failed!

### ISSUE THREAD

**Issue by Afeihan** [karpathy/neuraltalk2#158]
when I use the following command to run the code,I failed

      th eval.lua -model model_id1-501-1448236541.t7 -num_images 1000 -language_eval 1

The error message  as follows:

[index created!
tokenization...
Traceback (most recent call last):
  File "myeval.py", line 32, in <module>
    cocoEval.evaluate()
  File "/home/gu/neuraltalk2-master/coco-caption/pycocoevalcap/eval.py", line 31, in evaluate
    gts  = tokenizer.tokenize(gts)
  File "/home/gu/neuraltalk2-master/coco-caption/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
](url)

Can i get some relevant advice on how to solve this ?

**Comment by zzy-ucas** [comment]
@Afeihan I have met the same problem in `https://github.com/metrofun/AdaptiveAttention` and tried many ways. The reason is that the tool used in command `cmd` in

>         cmd = ['java', '-cp', STANFORD_CORENLP_3_4_1_JAR, 'edu.stanford.nlp.process.PTBTokenizer', '-preserveLines', '-lowerCase']

is not installed. So the FILE NOT FOUND is the TOOL `java` and cause the error here in

> p_tokenizer = subprocess.Popen(cmd, cwd=path_to_jar_dirname, stdout=subprocess.PIPE)

Hope this may help U!
