### ISSUE TITLE
Who explained for me, plz?

### ISSUE THREAD

**Issue by j2233ack** [karpathy/neuraltalk2#176]
Traceback (most recent call last):
  File "prepro.py", line 34, in <module>
    from scipy.misc import imread, imresize
ImportError: cannot import name imread

**Comment by j2233ack** [comment]
The new issue:
parsed input parameters:
{
  "output_json": "coco/cocotalk.json", 
  "images_root": "coco/images", 
  "input_json": "/home/hsu/Desktop/test.json", 
  "word_count_threshold": 5, 
  "max_length": 16, 
  "output_h5": "coco/cocotalk.h5", 
  "num_test": 33, 
  "num_val": 33
}
example processed tokens:
Traceback (most recent call last):
  File "prepro.py", line 240, in <module>
    main(params)
  File "prepro.py", line 162, in main
    prepro_captions(imgs)
  File "prepro.py", line 43, in prepro_captions
    txt = str(s).lower().translate(None, string.punctuation).strip().split()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)
