### ISSUE TITLE
language_eval error

### ISSUE THREAD

**Issue by MozhdehDokhani** [karpathy/neuraltalk2#201]
Hi,
When I run the following code, some error appears. Any solution?

`th eval.lua -model checkpoint_v1/model_id1-501-1448236541.t7 -image_folder img -num_images -1 -language_eval 1`
 -----------------------------------------------------------------------------------------------------
Error:
`Loading and preparing results...     
Traceback (most recent call last):
  File "myeval.py", line 29, in <module>
    cocoRes = coco.loadRes(resFile)
  File "/home/mozhdeh/Documents/neuraltalk2-master/coco-caption/pycocotools/coco.py", line 280, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
/home/mozhdeh/torch/install/bin/luajit: ./misc/utils.lua:17: attempt to index local 'file' (a nil value)
stack traceback:
	./misc/utils.lua:17: in function 'read_json'
	./misc/net_utils.lua:202: in function 'language_eval'
	eval.lua:167: in function 'eval_split'
	eval.lua:173: in main chunk
	[C]: in function 'dofile'
	...hdeh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x556c329a1570
`

**Comment by lin1061991611** [comment]
how did you sloved it now?

**Comment by mymuli** [comment]
我在neuraltalk2里面运行这个命令，没有报错....但是在e2e-LSTM-SC里面，遇到了同样的错误...还不知道怎么解决....

**Comment by lin1061991611** [comment]
> 决....

说出来你可能不信，我增加迭代次数后就没有“if 'caption' in anns[0]: IndexError: list index out of range ”这个错误了

**Comment by mymuli** [comment]
我现在有一个问题是，先训练完后CIDEr的分数只有0.67左右，然后怎么微调能达到A.K所说的0.9左右呢？能给我一点建议吗？期待...

**Comment by lin1061991611** [comment]
这个就不了解了，抱歉
