### ISSUE TITLE
Error with h5py in preprocessing

### ISSUE THREAD

**Issue by cuongduc** [karpathy/neuraltalk2#81]
I tried to run the preprocessing commands on MSCOCO data set:
`python prepro.py --input_json coco/coco_raw.json --num_val 5000 --num_test 5000 --images_root coco/MSCOCO --word_count_threshold 5 --output_json coco/cocotalk.json --output_h5 coco/cocotalk.h5`

But I got the following errors:

```
Traceback (most recent call last):
  File "prepro.py", line 32, in <module>
    import h5py
  File "/usr/lib/python2.7/dist-packages/h5py/__init__.py", line 16, in <module>
    from h5py import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
  File "h5t.pxd", line 14, in init h5py.h5a (h5py/h5a.c:6112)
  File "numpy.pxd", line 66, in init h5py.h5t (h5py/h5t.c:17955)
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /usr/lib/liblapack.so.3: undefined symbol: ATL_chemv
```
Has any one faced the same error and got the solution?

**Comment by cjds** [comment]
Have you written your own data into cocotalk.h5 or is this coco data

**Comment by cuongduc** [comment]
@cjds I thought it is the output file which will be produced after running the `prepro.py`?

**Comment by cjds** [comment]
@cuongduc Sorry my bad. Misread something. This is actually a documented problem not related with this but with ATLAS and numpy. 

[http://stackoverflow.com/questions/8917977/installing-lapack-for-numpy](http://stackoverflow.com/questions/8917977/installing-lapack-for-numpy)

Try above.

**Comment by cuongduc** [comment]
@cjds Thank you, it works perfectly!
